services:
  interfacewatcher_server:
    image: interfacewatcher-server
    container_name: interfacewatcher_server
    ports:
      - 3001:8080
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - common_bridge
networks:
  common_bridge:
    external: true
